services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production

  webapp:
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
    environment:
      - API_URL=http://api:3333
